# Generated by Django 5.2.11 on 2026-02-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_products',
        ),
    ]
